######################################################################
#
# File name : Array_8x8_tb_simulate.do
# Created on: Sun Jul 13 20:16:12 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.Array_8x8_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {Array_8x8_tb_wave.do}

view wave
view structure
view signals

do {Array_8x8_tb.udo}

run 1000ns
