######################################################################
#
# File name : Array_8x8_tb_wave.do
# Created on: Sun Jul 13 20:16:12 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
