######################################################################
#
# File name : Array_8x8_tb_compile.do
# Created on: Sun Jul 13 20:16:09 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -mfcu -work xil_defaultlib  \
"../../../../../Array_8x8.v" \
"../../../../../PE_STRAIT.v" \
"../../../../../Array_8x8_tb.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

